import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header className="bg-slate-300 p-3">
      <div>
        <nav className="flex justify-center">
          <Link className="mx-2 hover:underline" href="/">Snowtooth Mountain</Link>
          <Link className="mx-2 hover:underline" href="/mountain">Mountain</Link>
          <Link className="mx-2 hover:underline" href="/hotels">Hotels</Link>
          <Link className="mx-2 hover:underline" href="/contact">Contact</Link>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="max-w-2xl px-4 mx-auto mt-10">
          {children}
        </main>
      </body>
    </html>
  );
}
