import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Header() {
  return (
    <header class="bg-sky-100 p-3">
      <div>
        <nav class="flex justify-center">
          <Link class="mx-2 hover:underline" href="/">Home</Link>
          <Link class="mx-2 hover:underline" href="/mountains">Mountains</Link>
          <Link class="mx-2 hover:underline" href="/trees">Trees</Link>
          <Link class="mx-2 hover:underline" href="/contact">Contact</Link>
        </nav>
      </div>
    </header>
  )
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
